# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 08:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=200)),
                ('comments', models.TextField()),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OUTSTANDING', 'outstanding'), ('PAID', 'paid')], default='OUTSTANDING', max_length=11)),
                ('discount', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
